version: "master-{build}"

clone_depth: 1
skip_tags: true
skip_branch_with_pr: true
branches:
  only:
    - master

cache:
  - vendor/bundle

install:
  - ps: iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project chefdk -channel stable
  - ps: c:\opscode\chefdk\bin\chef.bat shell-init powershell | iex
  - SET PATH=C:\opscode\chefdk\embedded\mingw\bin;%PATH%
  - bundle config --local path vendor/bundle
  - SET CI=true

build_script:
  - bundle install

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake compile
  - bundle exec rake spec
